name: tabalt's blog
markdown: kramdown
#pygments: true
highlighter: rouge
baseurl: /
encoding: utf-8

#permalink: pretty
permalink: "/blog/:title/index.html"
paginate: 10
paginate_path: "page/:num"

gems: [jekyll-paginate]

#redcarpet:
#    extensions: ["tables", "autolink"]
