name: tabalt's blog
markdown: redcarpet
pygments: true
highlighter: pygments
baseurl: /
encoding: utf-8

#permalink: pretty
permalink: "/blog/:title"
paginate: 10
paginate_path: "page/:num"

redcarpet:
    extensions: ["tables", "autolink"]
