name: tabalt's blog
markdown: redcarpet
pygments: true
baseurl: /
encoding: utf-8

#permalink: pretty
permalink: /blog/:title
paginate: 3
paginate_path: "blog/page_:num"

redcarpet:
  extensions: ["tables", "autolink"]
